### PR TITLE
docs: Deploy documentation to Read the Docs

### PR DESCRIPTION
**Pull request by danielptv**
[ODDSK-136](https://h-ka-team-rdqzrlfpomci.atlassian.net/browse/ODDSK-136).

A link to the docs can be found in the updated README. To see the PR Preview click on *details* in the workflows section: https://open-data-dashboard--39.org.readthedocs.build/39/

### CODE REVIEW

**Review by Zerdados — COMMENTED** [review]
The configuration looks good, just one small thing I noticed: When I open the deployed documentation and switch the language to german, it doesn't look right. Are we aware of that?

**Comment by danielptv** [comment]
> The configuration looks good, just one small thing I noticed: When I open the deployed documentation and switch the language to german, it doesn't look right. Are we aware of that?

I am not quite sure what you mean. In the `latest` documentation (the link which is in the README) the language switcher is broken. In the [PR Preview](https://open-data-dashboard--39.org.readthedocs.build/39/) the German version of the site gets marked as "unsafe" by Chrome. I am not sure why but I hope it won't be the case when deployed to the actual domain rather than as PR preview.

Can you share the link in question which was broken for you?

**Comment by Zerdados** [comment]
> > The configuration looks good, just one small thing I noticed: When I open the deployed documentation and switch the language to german, it doesn't look right. Are we aware of that?
> 
> I am not quite sure what you mean. In the `latest` documentation (the link which is in the README) the language switcher is broken. In the [PR Preview](https://open-data-dashboard--39.org.readthedocs.build/39/) the German version of the site gets marked as "unsafe" by Chrome. I am not sure why but I hope it won't be the case when deployed to the actual domain rather than as PR preview.
> 
> Can you share the link in question which was broken for you?

The language switcher in the `latest` is not broken for me, it redirects me to this page: [https://open-data-dashboard.readthedocs.io/de/](https://open-data-dashboard.readthedocs.io/de/)

**Comment by danielptv** [comment]
> > > The configuration looks good, just one small thing I noticed: When I open the deployed documentation and switch the language to german, it doesn't look right. Are we aware of that?
> > 
> > 
> > I am not quite sure what you mean. In the `latest` documentation (the link which is in the README) the language switcher is broken. In the [PR Preview](https://open-data-dashboard--39.org.readthedocs.build/39/) the German version of the site gets marked as "unsafe" by Chrome. I am not sure why but I hope it won't be the case when deployed to the actual domain rather than as PR preview.
> > Can you share the link in question which was broken for you?
> 
> The language switcher in the `latest` doc is not broken for me, it redirects me to this page: https://open-data-dashboard.readthedocs.io/de/

Ah yeah, by broken I mean it redirects to the wrong URL. Check out the PR preview to see it working properly. Fix is in this PR in the `post_checkout` section of `readthedocs.yml`.²

**Comment by Zerdados** [comment]
> > > > The configuration looks good, just one small thing I noticed: When I open the deployed documentation and switch the language to german, it doesn't look right. Are we aware of that?
> > > 
> > > 
> > > I am not quite sure what you mean. In the `latest` documentation (the link which is in the README) the language switcher is broken. In the [PR Preview](https://open-data-dashboard--39.org.readthedocs.build/39/) the German version of the site gets marked as "unsafe" by Chrome. I am not sure why but I hope it won't be the case when deployed to the actual domain rather than as PR preview.
> > > Can you share the link in question which was broken for you?
> > 
> > 
> > The language switcher in the `latest` doc is not broken for me, it redirects me to this page: https://open-data-dashboard.readthedocs.io/de/
> 
> Ah yeah, by broken I mean it redirects to the wrong URL. Check out the PR preview to see it working properly. Fix is in this PR in the `post_checkout` section of `readthedocs.yml`.²

Ah, I get it now, thanks

**Review by Zerdados — APPROVED** [review]

**Pull request merged**
